image.url: '{cipher}ff7309c53eb4c6e9b8b8c6550138d5f5b923bbd8f7b5f3d6e5f7611854197869'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true


  cloud:
    config:
      server:
        git:
          uri: file:///home/nich/Documents/git-local-config-repo
  server:
    port: 8080
